name: Lint GitHub Actions workflows
on: [push, pull_request]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download actionlint
        id: get_actionlint
        shell: bash
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        shell: bash
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"

          # Disable shellcheck for now, as environment variables provided via the env: block are not detected and the SC2153 warning isu issued.
          ${{ steps.get_actionlint.outputs.executable }} -color --shellcheck="" 
  