name: Run Integration Tests
on: 
  workflow_call:
    inputs:
      runs-on:
        description: The type of machine to run the job on.
        type: string
        required: false
        default: ubuntu-latest
jobs:
  run_integration_test:

    name: Run Integration Tests
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Integration Test
        shell: bash
        run: |
          sudo apt-get install make
          make integration
